    <section class="page-header page-header-text-light bg-secondary">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8">
            <h1>Terms & Conditions</h1>
          </div>
          <div class="col-md-4">
            <ul class="breadcrumb justify-content-start justify-content-md-end mb-0">
              <li><a href="{site_url}home">Home</a> / Terms & Conditions</li>
            </ul>
          </div>
        </div>
      </div>
    </section><!-- Page Header end -->
    
  <!-- Content
  ============================================= -->
   <div id="content">
    <div class="container">
      <div class="bg-light shadow-md rounded p-4">
        <p>Welcome to cranesmart.in. <br />
Cranesbill Tradelink Private Limited provides access to the cranesmart.in website (the "website") to you subject to the conditions set out on this page.</p>
<p>Please read these conditions carefully before using the cranesmart.in website. By using the cranesmart.in website, you signify your agreement to be bound by these conditions.</p>
<p>In addition, when you use any current or future cranesmart.in service, you will also be subject to the terms, guidelines and conditions applicable to that service. If these Conditions of Use are inconsistent with such Terms, the Terms will control.</p>
<p>These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.

</p>
<p>1. Conditions Relating to Your Use of cranesmart.in</p>
<p>2. Notice and Procedure for Making Claims of Infringement</p>
<p>3. Notice and Procedure for Notifying cranesmart.in of Objectionable Content</p>
        <h2 class="text-6">Conditions Relating to Your Use of cranesmart.in</h2>
        <h3 class="text-4">1. Your Account</h3>
        <p>If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorized access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update most of the information you provided us directly. cranesmart.in reserves the right to refuse access to the website, terminate accounts, remove or edit content at any time without notice to you.</p>

        <h3 class="text-4">2. Privacy</h3>
        <p>Please review our Privacy Notice, which also governs your visit to cranesmart.in, to understand our practices. The personal information / data provided to us by you during the course of usage of cranesmart.in will be treated as strictly confidential and in accordance with the Privacy Notice and applicable laws and regulations. If you object to your information being transferred or used, please do not use the website.</p>

        <h3 class="text-4">3. E-Platform for Communication</h3>
        <p>You agree, understand and acknowledge that the website is an online platform that enables you to purchase products listed on the website at the price indicated therein at any time from any location. You further agree and acknowledge that Cranesmart is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the website. Accordingly, the contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on cranesmart.in</p>

        <h3 class="text-4">4. Access to cranesmart.in</h3>
        <p>We will do our utmost to ensure that availability of the website will be uninterrupted and that transmissions will be error-free. However, due to the nature of the Internet, this cannot be guaranteed. Also, your access to the website may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services and upgrade periodically at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction.</p>

        <h3 class="text-4">5. Licence for website access</h3>
        <p>Subject to your compliance with these Conditions of Use and payment of applicable fees, if any, Cranesbill Tradelink Private Limited grants you a limited licence to access and make personal use of this website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Cranesbill Tradelink Private Limited and / or its affiliates, as may be applicable. This licence does not include any resale or commercial use of this website or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this website or its contents; any downloading or copying of account information for the benefit of another seller; or any use of data mining, robots, or similar data gathering and extraction tools.
This website or any portion of this website (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of Cranesbill Tradelink Private Limited and / or its affiliates, as may be applicable.</p>
<p>
You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of cranesmart.in and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilizing Cranesbill Tradelink Private Limited's or its affiliates' names or trademarks without the express written consent of Cranesbill Tradelink Private Limited and / or its affiliates, as applicable. Any unauthorized use terminates the permission or licence granted by Cranesbill Tradelink Private Limited and / or its affiliates, as applicable.</p>
<p>
You are granted a limited, revocable, and non-exclusive right to create a hyperlink to the Welcome page of cranesmart.in as long as the link does not portray Cranesbill Tradelink Private Limited, cranesmart.in, their affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any cranesmart.in logo or other proprietary graphic or trademark as part of the link without express written consent of Cranesbill Tradelink Private Limited and / or its affiliates, as may be applicable.
</p>
<h3 class="text-4">6. Your Conduct</h3>
        <p>You must not use the website in any way that causes, or is likely to cause, the website or access to it to be interrupted, damaged or impaired in any way. You understand that you, and not cranesmart.in, are responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only. You must not use the website for any of the following:</p>
<p>1. for fraudulent purposes, or in connection with a criminal offense or other unlawful activity</p>
<p>2. to send, use or reuse any material that does not belong to you; or is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, pedophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam”</p>
<p>3. to cause annoyance, inconvenience or needless anxiety
</p>

<h3 class="text-4">7. Reviews, comments, communications and other content</h3>
        <p>Users of this website may post reviews, comments and other content; send communications; and submit suggestions, ideas, comments, questions, or other information, as long as the content is not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties, or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." In the event a user uses a false e-mail address, impersonates any person or entity, or otherwise misleads as to the origin of any content, cranesmart.in reserves the right (but not the obligation) to remove, refuse, delete or edit any content that at the sole judgement of cranesmart.in violates these Conditions of use and, or terminate your permission to access or use this website.</p>
<p>If you do post content or submit material, and unless we indicate otherwise, you</p>
<p>1.  (a) grant Cranesbill Tradelink Private Limited and its affiliates a non-exclusive, royalty-free, irrevocable, perpetual and fully sub licensable rights to use, reproduce, modify, adapt, publish, translate, create derivative works form, distribute, and display such content throughout the world in any media; and</p>
<p>2.  (b) Cranesbill Tradelink Private Limited and its affiliates and sub licensees, the right to use the name that you submit in connection with such content, if they choose.</p>
<p>
You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. You agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Cranesbill Tradelink Private Limited, including the execution of deeds and documents, at its request.</p>
<p>You represent and warrant that you own or otherwise control all of the rights to the content that you post or that you otherwise provide on or through the website; that, as at the date that the content or material is submitted to cranesmart.in: (i) the content and material is accurate; (ii) use of the content and material you supply does not breach any applicable cranesmart.in policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory); (iii) the content is lawful. You agree to indemnify Cranesbill Tradelink Private Limited and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.
</p>

<h3 class="text-4">8. Claims against Objectionable Content</h3>
        <p>Because cranesmart.in lists millions of products for sale offered by sellers on the website and hosts many thousands of comments, it is not possible for us to be aware of the contents of each product listed for sale, or each comment or review that is displayed. Accordingly, cranesmart.in operates on a "notice and takedown" basis. If you believe that any content on the website is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, pedophilic or menacing; ethnically objectionable, disparaging; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, ("Objectionable Content"), please notify us immediately. Once this procedure has been followed, cranesmart.in will make all reasonable endeavors to remove such Objectionable Content complained about within a reasonable time.</p>

<h3 class="text-4">9. Copyright, authors' rights and database rights</h3>
        <p>All content included on the website, such as text, graphics, logos, button icons, images, audio clips, graphics, images, digital downloads, data compilations, and software, is the property of Cranesbill Tradelink Private Limited, its affiliates or its content suppliers and is protected by India and international copyright, authors' rights and database right laws. The compilation of all content on this website is the exclusive property of Cranesbill Tradelink Private Limited and its affiliates and is protected by laws of India and international copyright and database right laws. All software used on this website is the property of Cranesbill Tradelink Private Limited, its affiliates or its software suppliers and is protected by India and international copyright and author' rights laws.</p>
        <p>
You may not systematically extract/ or re-utilise parts of the contents of the website without Cranesbill Trdelink Private Limited and / or its affiliate's (as may be applicable) express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilization of any substantial parts of this website, without Cranesbill Tradelink Private Limited and / or its affiliate's (as may be applicable) express written consent. You may also not create and/ or publish your own database that features substantial (eg: prices and product listings) parts of this website without Cranesbill Tradelink Private Limited and / or its affiliates’ (as may be applicable) express written consent.
</p>        
<h3 class="text-4">10. Intellectual Property Claims</h3>
        <p>Cranesbill Tradelink Private Limited and its affiliates respect the intellectual property of others. If you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement, please bring to our notice and we shall take suitable remedial action.</p>

<h3 class="text-4">11. Disclaimer</h3>
        <p>You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through the website. You further acknowledge and undertake that you will use the website to order products only for your personal use and not for business purposes. We shall neither be liable nor responsible for any actions or inactions of sellers nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between you and the sellers or manufacturers of the products.</p>
        <p>
We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services and related graphics are provided as is, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any products on the website. At no time shall any right, title or interest in the products sold through or displayed on the website vest with Cranesmart nor shall Cranesmart have any obligations or liabilities in respect of any transactions on the website.
</p>        

<h3 class="text-4">12. Indemnity and Release</h3>
        <p>You shall indemnify and hold harmless Cranesbill Tradelink Private Limited, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Conditions of Use or any document incorporated by reference, or your violation of any law, rules, regulations or the rights of a third party.</p>
        <p>
You hereby expressly release Cranesbill Tradelink Private Limited and/or its affiliates and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waive any claims or demands that you may have in this behalf under any statute, contract or otherwise.
</p>
<h3 class="text-4">13. Children</h3>
        <p>Use of cranesmart.in is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may use cranesmart.in only with the involvement of a parent or guardian.</p>

<h3 class="text-4">14. Other Businesses</h3>
        <p>Parties other than Cranesmart Tradelink Private Limited and its affiliates may operate stores, provide services, or sell product lines on cranesmart.in. For example, businesses and individuals offer products via Marketplace. In addition, we provide links to the websites of affiliated companies and certain other businesses. We are not responsible for examining or evaluating, and we do not warrant or endorse the offerings of any of these businesses or individuals, or the content of their websites. Cranesbill Tradelink Private Limited does not assume any responsibility or liability for the actions, products, and content of any of these and any other third parties. You can tell when a third party is involved in your transactions, and we may share customer information related to those transactions with that third party. You should carefully review their privacy statements and other conditions of use.</p>        

<h3 class="text-4">15. Communications</h3>
        <p>When you visit cranesmart.in, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, sms, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications (including transactional, promotional and/or commercial messages), from us with respect to your use of the website and/or your order placed on the website.</p>                

<h3 class="text-4">16. Losses</h3>
        <p>We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when you commenced using the website.</p>

<h3 class="text-4">17. Alteration of Service or Amendements to the Conditions</h3>
        <p>We reserve the right to make changes to our website, policies, and these Conditions of Use at any time. You will be subject to the policies and Conditions of Use in force at the time that you use the website or that you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p>

<h3 class="text-4">18. Events beyond our reasonable control</h3>
        <p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.</p>        

<h3 class="text-4">19. Waiver</h3>
        <p>If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.</p>

<h3 class="text-4">20. Governing law and Jurisdiction</h3>
        <p>These conditions are governed by and construed in accordance with the laws of India. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Delhi.</p>


<h3 class="text-4">21. Our Details</h3>
        <p>This website is operated by Cranesbill Tradelink  Private Limited.</p>
<p>For the cranesmart.in website, you could contact us by writing email to us at <b>info@cranesmart.in</b>
</p>
<h3 class="text-4">22. Cranesmart Software Terms</h3>
        <p>In addition to these Conditions of Use, the terms apply to any software (including any updates or upgrades to the software and any related documentation) that we make available to you from time to time for your use in connection with cranesmart.in  services.</p>

<h3 class="text-4">23. Sanctions and Export Policy</h3>
        <p>You may not use any Cranesmart service if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using cranesmart services. You must comply with all U.S. or other export and re-export restrictions that may apply to goods, software (including Cranesmart Software), technology and services.</p>        

<h3 class="text-4">24. Notice and Procedure for Making Claims of Right Infringements</h3>
        <p>If you believe that your rights are being infringed, you may <b>write to us by email at info@cranesmart.in</b>. We respond expeditiously to rights owners and their agents who submit the email to communicate concerns about any alleged infringement.</p>
<p>Upon receipt of email we may take certain actions, including removing information or an item, all of which are taken without any admission as to liability and without prejudice to any rights, remedies or defenses, all of which are expressly reserved. Furthermore, by submitting email, you grant to cranesmart the right to use, reproduce, modify, adapt, publish, translate, create derivative works form, and display its content throughout the world in any media. This includes forwarding the Notice to the parties involved in the provision of the allegedly infringing content. You agree to indemnify cranesmart.in for all claims brought by a third party against cranesmart.in arising out of or in connection with the writing of email.
</p>               
<p><b>Note on Third Party Seller Listings:</b> Please keep in mind that Third Party Seller listings are merely hosted on cranesmart.in and are posted solely at the direction of Third Party Sellers who may be contacted via their "Seller Information" page, accessible from any of their listings.</p>
<p>
CSIN and ISBN-10, Defined: "CSIN" stands for Cranesmart Standard Item (or Identification) Number and is a ten (10) character identifier. It can be found below any listing under "Product Details". "ISBN-10" stands for International Standard Book Number and is a ten (10) digit identifier that can be found on some book listings under "Product Details".</p>
<p><b>
Important Warning:</b> giving false, misleading or inaccurate information in the Notice email to cranesmart may result in civil and/or criminal liability. You should contact a legal advisor should you have any questions.</p>
<p><b>
Notice and Procedure for Notifying cranesmart.in of Objectionable Content</b></p>
<p>
If you believe that any content, or advertised for sale on the website contains any Objectionable Content, please notify us immediately by copying the Objectionable Content to cranesmart.in and send a signed copy via E-mail PDF to </p>
<p>
<b>e-mail PDF:</b> info@cranesmart.in</p>
<p><b>Subject Line:</b> Claim of Objectionable Content</p>
<p>or</p>
<p>Cranesbill Tradelink Private Limited</p>
<p>Property no.79, 3rd Floor, DSIIDC Scheme 1</p>
<p>Okhla Industrial area Phase II</p>
<p>New Delhi – 110 020, India</p>
<p>Please note that this procedure is exclusively for notifying cranesmart.in of Objectionable Content on or advertised for sale on the cranesmart.in website. Please provide your address, telephone number, and e-mail address when sending the notice to us.</p>
<p><b>Important Warning:</b> Giving false, misleading or inaccurate information in the Notice to cranesmart.in may result in civil and/ or criminal liability.
</p> 


<h2 class="text-6">Cranesmart Software Terms</h2>
        <h3 class="text-4">1. Use of the cranesmart Software</h3>
        <p>You may use cranesmart Software solely for purposes of enabling you to use and enjoy the cranesmart Services as provided by cranesmart, and as permitted by the Conditions of Use and any Terms. You may not incorporate any portion of the cranesmart Software into your own programs or compile any portion of it in combination with your own programs, transfer it for use with another service, or sell, rent, lease, lend, loan, distribute or sub-license the cranesmart Software or otherwise assign any rights to the cranesmart Software in whole or in part. You may not use the cranesmart Software for any illegal purpose. We may cease providing any cranesmart Software and we may terminate your right to use any cranesmart Software at any time. Your rights to use the cranesmart Software will automatically terminate without notice from us if you fail to comply with any of these cranesmart Software Terms, the Conditions of Use or any other Terms. Additional third party terms contained within or distributed with certain cranesmart Software that are specifically identified in related documentation may apply to that cranesmart Software (or software incorporated with the cranesmart Software) and will govern the use of such software in the event of a conflict with these Conditions of Use. All software used in any cranesmart Service is the property of cranesmart and/or its affiliates or its software suppliers and protected by laws of India including but not limited to any other applicable copyright laws.</p>

        <h3 class="text-4">2. Use of Third Party Services</h3>
        <p>When you use the cranesmart Software, you may also be using the services of one or more third parties, such as a wireless carrier or a mobile platform provider. Your use of these third party services may be subject to the separate policies, terms of use, and fees of these third parties.</p>

        <h3 class="text-4">3. No Reverse Engineering</h3>
        <p>You may not, and you will not encourage, assist or authorize any other person to copy, modify, reverse engineer, decompile or disassemble, or otherwise tamper with, the cranesmart Software, whether in whole or in part, or create any derivative works from or of the cranesmart Software.</p>

        <h3 class="text-4">Updates</h3>
        <p>In order to keep the cranesmart Software up-to-date, we may offer automatic or manual updates at any time and without notice to you.</p>
        <p><b>Conditions of Sale (between Sellers and the Customer) <br />
Please read these conditions carefully before placing an order for any products with the Sellers ("We" or "Our" or "Us", wherever applicable) on the cranesmat.in (the website). These conditions signify your agreement to be bound by these conditions.
</b></p>
<p>In addition, when you use any current or future cranesmart.in service (eg: Wishlist or Marketplace), you will also be subject to the terms, guidelines and conditions applicable to that service ("Terms"). If these Conditions of Sale are inconsistent with such Terms, the Terms will control.</p>
<h3 class="text-4">1. Conditions Relating to the Sale of Products to You</h3>
        <p>This section deals with conditions relating to the sale of products on the website by us to you.</p>
<h3 class="text-4">2. Our Contract</h3>
        <p>Your order is an offer to us to buy the product(s) in your order. When you place an order to purchase a product from us, you will receive notification by an e-mail or sms confirming receipt of your order and containing the details of your order (the "order notification"). The notification is acknowledgement that we have received your order, and does not confirm acceptance of your offer to buy the product(s) ordered. We only accept your offer, and conclude the contract of sale for a product ordered by you, when the product is dispatched to you and a notification is sent to you that the product has been dispatched to you (the "Dispatch notification"). If your order is dispatched in more than one package, you may receive a separate Dispatch notification for each package, and each Dispatch notification and corresponding dispatch will conclude a separate contract of sale between you and us for the product(s) specified in that Dispatch notification.</p>
        <p>
Your contract is with us (the Sellers) and you confirm that the product(s) ordered by you are purchased for your internal / personal purpose and not for re-sale or business purpose. You authorize us to declare and provide declaration to any governmental authority on your behalf stating the aforesaid purpose of the products ordered by you on the website.
You can cancel your order for a product at no cost any time before we send the Dispatch notification relating to that product.</p>
<p>
Please note that we sell products only in quantities which correspond to the typical needs of an average household. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity typical for a normal household.
</p>       

<h3 class="text-4">3. Returns</h3>
        <p>Please review our Returns Policy, which applies to products sold by us.</p> 

<h3 class="text-4">4. Pricing and availability</h3>
        <p>We list availability information for products sold by us on the website, including on each product information page. Beyond what we say on that page or otherwise on the website, we cannot be more specific about availability. Please note that dispatch estimates are just indicative. They are not guaranteed dispatch times and should not be relied upon as such. As we process your order, you will be informed by e-mail or sms if any products you order turn out to be unavailable.</p>
        <p>
All prices are inclusive of VAT/CST, service tax, Goods and Services Tax ("GST"), duties and cesses as applicable - unless stated otherwise.
</p>       
<h3 class="text-4">5. Taxes</h3>
        <p>You shall be responsible for payment of all fees/costs/charges associated with the purchase of products from us and you agree to bear any and all applicable taxes including but not limited to VAT/CST, service tax, GST, duties and cesses etc.</p>  

<h3 class="text-4">6. Health & Safety</h3>
        <p>By purchasing any product from our Home & Kitchen shop, you acknowledge that you have read and understood our Health & Safety Guidelines.</p>          

<h3 class="text-4">7. Children</h3>
        <p>Use of cranesmart.in is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may purchase only with the involvement of a parent or guardian.</p>                  

<h3 class="text-4">8. Communications</h3>
        <p>When you visit cranesmart.in, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications including SMS, e-mails or phone calls from us with respect to your order.</p>

<h3 class="text-4">9. Losses</h3>
        <p>We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when a contract for the sale of goods by us to you was formed.</p>

<h3 class="text-4">10. Alteration or Amendments to the Conditions</h3>
        <p>We reserve the right to make changes to our policies, and these Conditions of Sale at any time. You will be subject to the policies and Conditions of Sale in force at the time you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p>        

<h3 class="text-4">11. Events beyond our reasonable control</h3>
        <p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.</p>                

<h3 class="text-4">12. Waiver</h3>
        <p>If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.</p>

<h3 class="text-4">13. Governing Law and Jurisdiction</h3>
        <p>These conditions are governed by and construed in accordance with the laws of India, and the application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Delhi.</p>



      </div>
    </div>
    
  </div><!-- Content end -->